### PR TITLE
facet_wrap labeller; horizontal linerange; spelling fixes

### PR DESCRIPTION
**Pull request by bbolker**
too much at once here, sorry -- but I hope this is useful.

### CODE REVIEW

**Comment by hadley** [comment]
Would you mind splitting up into smaller pieces?  It's going to be really hard to merge this because of all the documentation changes we've been doing.  Just bad timing unfortunately :(

**Comment by bbolker** [comment]
I think the easiest thing to do will be for me to nuke these changes and start again from the current version (it would be different if my Github-fu were better).  I know you're hoping to release soon ... what is the timescale for these?  (I think the most interesting one is the `facet_wrap` labeller capability, which is a couple of lines I stole from someone else's fork ...)

**Comment by hadley** [comment]
Aiming to be done with the book before the JSM, and hopefully package too. So ~ 3 weeks?

**Comment by bbolker** [comment]
seems feasible.  thanks.

**Comment by hadley** [comment]
Also, don't worry about the import stuff - we'll do that ourselves

**Comment by lionel-** [comment]
Hi @bbolker 

The labeller stuff is being addressed in #1127.

**Pull request closed without merging**
