### PR TITLE
Documentation tweaks

### PR DESCRIPTION
**Pull request by joranE**
Some minor changes & clarifications to guides and scales. Main change is the explicit documentation of the inherit.aes, subset and show_guide arguments for geoms, rather than then redirecting people to layer, which has no documentation.

### CODE REVIEW

**Comment by hadley** [comment]
I like the basic idea, but I'd like to downplay `subset`, so I'd prefer it not be included by default.  And `inherit.aes` is rather esoteric, and shouldn't be needed by the end user, so I'd rather keep that out too. You would mind updating with that in mind?

(And also could you please squash the commits down to just one or two)

**Comment by joranE** [comment]
Is your concern that `subset` and `inherit.aes` might go away at some point and you don't want them made "official"? The reason I ask is just to clarify whether you would you prefer no mention of the availability of `subset` and `inherit.aes` at all, or whether they could be mentioned under the `...` argument but with a warning that their functionality may change or disappear in the future?

**Comment by hadley** [comment]
They're not going to go away, but equally I don't want people using them.

**Comment by joranE** [comment]
Ok...I hope I navigated all the git squashing correctly...

**Comment by hadley** [comment]
Could you please use the latest version of roxygen?  Squashing looks good

**Comment by joranE** [comment]
Sorry...so many little details to remember! :) Does that look better?

**Comment by hadley** [comment]
Thanks - I really appreciate the improvement due to the extreme fiddliness!  Any interest in doing similar work for the scales? I'm also thinking about documenting more of the stat arguments in the corresponding geom.

**Comment by joranE** [comment]
No problem! I'd be happy to look at the scales and see what I can do. If there's anything specific bothering you about them, that would be helpful to know...

**Comment by hadley** [comment]
Just the same problem as the geoms - that there's a big ... full of important arguments, and you have to go hunting around the docs to figure out the complete set of arguments that a function understands

**Pull request merged**
