### PR TITLE
Change meaning of trim in geom_violin

### LINKED ISSUE #1793: Violin plots are not trimmed correctly
Opening this so that it doesn't get forgotten. See discussion in  #1783.

### PR DESCRIPTION
**Pull request by thomasp85**
Fixes #1793

This PR changes the trim behaviour back to how it worked in v1.x.x

### CODE REVIEW

**Comment by thomasp85** [comment]
@hadley @wch should this be the behaviour?

```r
df <- data.frame(a = c(1:100),b=c(rep(0,50),rep(1,50)))
ggplot(df,aes(y=a,x=factor(b))) + geom_violin(trim=TRUE)
```
rplot
```r
ggplot(df,aes(y=a,x=factor(b))) + geom_violin(trim=FALSE)
```
rplot01
```r
no_range <- data.frame(x = factor(rep(1, 10)), y = rep(0, 10))
ggplot(no_range, aes(x, y)) + geom_violin(trim = TRUE)
```
rplot02
```r
ggplot(no_range, aes(x, y)) + geom_violin(trim = FALSE)
```
rplot03

**Comment by wch** [comment]
Looks good to me.

**Comment by thomasp85** [comment]
@hadley ?

**Comment by hadley** [comment]
LGTM

**Pull request merged**
