### PR TITLE
Strip text rotated opposite dir to axis text (derived themes)

### PR DESCRIPTION
**Pull request by lionel-**
Actually not due to your refactor but to this old regression in #1263

### CODE REVIEW

**Comment by hadley** [comment]
Oh hmmm. That will just break the second issue again

**Comment by lionel-** [comment]
In https://github.com/hadley/ggplot2/commit/3a33d34a7a6046498100496d372ad38bab3a8951 you set `strip.text.y`'s angle back to -90 for `theme_grey()` but not `theme_light()` and `theme_dark()`.

**Comment by lionel-** [comment]
To be clear, the labels were wrong when switched but actually also unswitched, because I was using `theme_light()` ;)

**Comment by hadley** [comment]
Oooooooooh I see. Thanks!

**Pull request merged**
