### PR TITLE
theme(validate=FALSE) means do not validate_element

### PR DESCRIPTION
**Pull request by tdhock**
This allows support for non-standard theme options, which would close

https://github.com/hadley/ggplot2/issues/938

### CODE REVIEW

**Comment by tdhock** [comment]
@wch @hadley can you please take a look at merging this? It is causing us problems in animint.

https://github.com/tdhock/animint/issues/29

**Comment by tdhock** [comment]
actually this was due to a bug in tdhock/ggplot2 which I just fixed (and added tests for)

**Comment by wch** [comment]
I'm a bit reluctant to add an option like this... Could you implement the animint theme options by attaching them as an attribute to the ggplot object? Getting that to play well with the `+` operator may be tricky though.

**Comment by tdhock** [comment]
Dear @wch, thanks for considering my PR, and thanks for your concerns.

Can you please clarify why exactly you are reluctant to add such an option? It seems to me that it is completely backwards compatible with existing ggplots. I even added some unit tests in test-theme.R to make sure that validate=FALSE is respected.

I haven't had time to try implementing it as an attribute of the ggplot object, but thanks for the suggestion.

**Comment by antongrau** [comment]
I would like this merge to go through. I am implementing animint in three R-packages and I need the custom theme functions.

**Comment by hadley** [comment]
Can you please post a clean PR for review? (i.e. unmodified readme & [house style](http://r-pkgs.had.co.nz/r.html#style))

**Comment by tdhock** [comment]
Please review #1121 which includes an unmodified readme and spaces before and after = and + operators.

**Pull request closed without merging**
