### PR TITLE
Finished removing qplot

### PR DESCRIPTION
**Pull request by hrbrmstr**
The only places `qplot` remains are in:

- `quick-plot.r`
- `translate-qplot-base.r`
- `translate-qplot-ggplot.r`
- `translate-qplot-gpl.r`
- `translate-qplot-lattice.r`

### CODE REVIEW

**Comment by hrbrmstr** [comment]
I also tried to clean up spacing around `=` when those were noticed and there were some errors in the examples that I also fixed.

**Comment by hadley** [comment]
Thanks! This looks great. Would you mind merging/rebasing and adding a bullet to NEWS?

**Comment by hrbrmstr** [comment]
will do.

**Comment by hadley** [comment]
Actually I'll merge myself since I need to make some other changes to the examples.

**Comment by hrbrmstr** [comment]
Roger that. If possible, please keep in the change I made to the US map
plot (added an albers projection). Every new R user wanting to make a US
map uses that ggplot documentation example and produces horrible mercator
US maps from it. At least now future US maps from new R folk might use a
proper projection ;-)

**Comment by hadley** [comment]
Will do! Also any interest in this? https://github.com/AndySouth/rworldmap/issues/4

**Pull request merged**
