### PR TITLE
Don't use alpha for violin quantiles

### PR DESCRIPTION
**Pull request by mnbram**
See #1714

### CODE REVIEW

**Comment by thomasp85** [comment]
This seems reasonable to me - @hadley can you comment?

It will need a news bullet once Hadley approves. I don't think unit tests makes sense for this

**Comment by hadley** [comment]
Seems reasonable to me, but I'd like to see a pair of before/after images in this PR.

**Comment by mnbram** [comment]
**Before:**
before

**After:**
after

**Comment by hadley** [comment]
LGTM

**Comment by thomasp85** [comment]
@mnbram can you add a news bullet?

**Comment by mnbram** [comment]
@thomasp85 Sorry, I'm new to this and I don't know what that means. Do you just want a brief summary of the change, like: "Quantile lines in geom_violin() are no longer affected by the alpha aesthetic"?

**Comment by thomasp85** [comment]
Yep - something like that. And then mention the issue number

**Comment by mnbram** [comment]
OK. I now see from looking at other pull requests that this should go in NEWS.md with a new commit, correct? At the bottom of the ggplot2 2.1.0.9000 section?

**Comment by thomasp85** [comment]
Precisely

**Comment by mnbram** [comment]
Sorry, I appear to have mangled things while trying to update NEWS.md. I'm working on fixing it, but obviously I am not a git expert.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
