### PR TITLE
theme(validate=FALSE) means do not validate_element (clean)

### PR DESCRIPTION
**Pull request by tdhock**
This is a cleaner version of https://github.com/hadley/ggplot2/pull/953#issuecomment-111270357

### CODE REVIEW

**Comment by hadley** [comment]
@wch this seems like a reasonable strategy to me. Can you please confirm?

**Comment by hadley** [comment]
Looks good. Can you please add a bullet point to NEWS following the standard format?

**Comment by tdhock** [comment]
is that OK?

**Comment by hadley** [comment]
Yup, thanks!

**Pull request merged**
