### PR TITLE
Allow to reverse the order of colours in a brewer palette

### PR DESCRIPTION
**Pull request by jiho**
Use the same argument that scale_*_hue uses: direction

### CODE REVIEW

**Comment by hadley** [comment]
Can you please merge/rebase?  If it still needs the dev version of scales, can you please update the DESCRIPTION?

**Comment by jiho** [comment]
Ideally, I would need you to pull #1076 first. Then I'll rebase (or more probably just completely rewrite) this on top of it. The changes in `scales` are minimal (https://github.com/hadley/scales/pull/36) but should be released in order for this to not depend on a dev version of scales, which is probably unsuitable.

Do you plan on releasing scales also?

**Comment by hadley** [comment]
I'm planning on releasing scales tomorrow.

**Comment by hadley** [comment]
Can you please finish this off now that scales is out? You'll need to add an explicit version requirement in the DESCRIPTION

**Comment by jiho** [comment]
#1139 replaces this one (much simpler thanks to the change in scales and branches from a recent master)

**Pull request closed without merging**
