### PR TITLE
New theme_void(), completely empty

### PR DESCRIPTION
**Pull request by jiho**

### CODE REVIEW

**Comment by hadley** [comment]
Can you please merge/rebase?

**Comment by hadley** [comment]
(BTW I'm going to be working on ggplot2 + the book for the next two weeks, so now is a good time if there's other stuff you'd like to submit)

**Comment by jiho** [comment]
Rebased on current master and fix the NEWS bullet (put outside of release and remove extraneous piece that were committed by mistake)

**Comment by jiho** [comment]
Had to force push so the original comments here seem to be gone.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
