### PR TITLE
Various fixes to themes

### PR DESCRIPTION
**Pull request by jiho**
Make both the code and the visual aspect of all theme more homogeneous. The general idea was to take theme_grey as the reference for all changes (and since it changed slightly in the previous update of ggplot2, the other themes needed some love too!).

I tried to divide the PR in small standalone commits (too lazy for several pull requests ;-) ). I'll update them as needed so that the show PR can be merged. I also added the rationale for various choices as comments in the code.

Some fixes were clearly needed (default size, etc.). Visually, I think theme_bw in particular needed a review. For the others, the changes are quite subtle.

### CODE REVIEW

**Comment by jiho** [comment]
Some before-after shots; current stable on the left, new version after these commits on the right
compare002
compare003
compare004
compare005
compare006
compare007
compare008
compare009

**Comment by hadley** [comment]
Does this connect to #1581 in any way?

I never really use themes, so I'd also be open to suggestions about how to decrease the likelihood of regressions when I merge future PRs.

**Comment by jiho** [comment]
I don't think it relates to #1581 in any way. I think the point of that PR is well made. Once it is merged, it would (marginally) simplify some of the theme specifications but it should not create any regression.

As for regressions for the changes in this PR, it depends what you would call a regression. Some commits here do *change* the visual aspect. I think for the better but some might say any change is a regression at this point. You have the before-after shots to judge which are acceptable. I think the most problematic, potentially, would be `theme_bw`, which is the probably the most used and the one I changed the most. I think the previous version had serious issues (colors, minor grid larger than major grid, etc.).

PS: The merge tool says there are conflicts but I just branched from master a few days ago. I've changed the commits to solve a Travis error; do do so I've had to force push the new commits. Maybe this throws the merge tool astray. Let me know if you want to rebase.

**Comment by hadley** [comment]
Ok, sounds reasonable.  If you rebase, I'll merge.

**Comment by Katiedaisey** [comment]
I'll check more closely later with some edge cases but I see no obvious conflict with #1581. This seems to standardize the defaults while #1581 incorporates values from more general parent elements when intermediate elements are not specified.

**Comment by jiho** [comment]
I've rebased. I'm not sure what that failing check means...

**Comment by hadley** [comment]
Thanks! The failing check is just for unit tests, which don't matter here

**Comment by jiho** [comment]
That was quick, thanks. Do you want me to test how #1728 behaves after this merge?

**Comment by hadley** [comment]
I'll update that branch, but I think it should be largely independent.

**Comment by krlmlr** [comment]
Is there a convenient way to access the old definitions? I need to retrofit a `theme_bw()` plot to the old look, my current workaround is to install ggplot2 2.1.0 :-/

**Comment by jiho** [comment]
You can probably pull the file with the definitions from 2.1.0 and override the new ones by sourcing just this file... unless this was before the theming system changed.

**Pull request merged**
